linkedin/kafka-monitor

.gitignore
docker/Dockerfile
docker/Makefile
docker/README.md
docker/kafka-monitor-docker-entry.sh

make this an image my friends!

add a Docker build folder with makefile

---

gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle to 3.2.1

---

services/src/main/java/com/linkedin/kmf/common/DefaultTopicFactory.java
services/src/main/java/com/linkedin/kmf/common/TopicFactory.java
services/src/main/java/com/linkedin/kmf/common/Utils.java
services/src/main/java/com/linkedin/kmf/producer/KMBaseProducer.java
services/src/main/java/com/linkedin/kmf/services/ProduceService.java
services/src/main/java/com/linkedin/kmf/services/configs/ProduceServiceConfig.java
services/src/main/java/com/linkedin/kmf/services/configs/TopicManagementServiceConfig.java

Also some documentation changes to KMBaseConsumer and KMBaseProducer.

User configurable topic factory to create the monitored topic.

---

build.gradle

For now hardcode the version number field in the build.gradle file.  Version numbering based on git tags coming soon.

Set a version number.

---

config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/apps/MirrorPipelineMonitor.java
src/main/java/com/linkedin/kmf/common/Utils.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java
src/main/java/com/linkedin/kmf/services/configs/TopicManagementServiceConfig.java

Set the initial delay for the topic management factory thread to be zero.
Let the topic factory deal with existing topic.

Pass the configuration parameters to the topic factory.

---

src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java

Otherwise the topic management service can exit.

Catch AdminOperationException

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/DefaultMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/JettyService.java
src/main/java/com/linkedin/kmf/services/JolokiaService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/Service.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java
src/test/java/com/linkedin/kmf/KafkaMonitorTest.java

This protects the monitor state when it is run in a container.

Synchronize KafkaMonitor methods

---

.gitignore
config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/common/Utils.java
src/main/java/com/linkedin/kmf/services/KafkaMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/configs/KafkaMetricsReporterServiceConfig.java
src/main/java/com/linkedin/kmf/topicfactory/DefaultTopicFactory.java

A demand to send metrics to Kafka,then other applications could consume from Kafka for further processing or compute.

Add KafkaMetricsReporterService to support send metrics to kafka

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
webapp/index.html

Add 9999th produce delay and records delay

Add 9999th produce delay and records delay

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java

Addition of Tracelogs for **recordsLost** in _Consume Service_ to indicate record index and the next index.

Addition of Tracelogs for recordsLost in Consume Service 

---

CODE_OF_CONDUCT.md

Add KMF's Contributor Covenant Code of Conduct

KMF's Contributor Covenant Code of Conduct

---

src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

**Single Cluster** Monitoring - ensure there are no _static_ imports.

Single Cluster Monitoring: ensure there are no static imports.

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java
src/main/java/com/linkedin/kmf/common/DefaultTopicSchema.java
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/GraphiteMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/KafkaMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/services/SignalFxMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/StatsdMetricsReporterService.java

Executor fixed rated schedulings lamda conversions from Runnables for services

Executor Fixed rated schedulings Runnable -> lamda conversions

---

README.md

Update `README` _Markdown_ with **xinfra** health monitor logo.

Update README Markdown with xinfra health monitor logo

---

src/main/java/com/linkedin/kmf/apps/MultiClusterMonitor.java
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java
src/main/java/com/linkedin/kmf/tests/BasicEndToEndTest.java

Appropriate variable naming conventions

Appropriate variable naming conventions

---

README.md

Secure Sockets Layer (SSL) or any non-plaintext security protocol AdminClient
SSL or any non-plaintext security protocols config

SSL or any non-plaintext security protocols config

---

config/kafka-monitor.properties

Secure Socket Layer security protocol properties

Secure Socket Layer security protocol properties

---

README.md

Placement of Kafka Monitor Logo and enlarge.

Placement of Kafka Monitor Logo and enlarge.

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java

Factor common variables in produceService into class variables.

Factor common variables in produceService into class variables.

---

src/main/java/com/linkedin/kmf/services/ProduceService.java
src/test/java/com/linkedin/kmf/KafkaMonitorTest.java

checkstyle conventions and redunant uages of .this

checkstyle conventions and redunant uages of .this

---

semantic-build-versioning.gradle

Commenting on semantic-build-versioning.gradle file

Commenting on semantic-build-versioning.gradle file

---

config/multi-cluster-monitor.properties

Added metrics to the Reporter Service on multi cluster monitoring.

Added metrics to the Reporter Service on multi cluster monitoring.

---

src/main/java/com/linkedin/kmf/consumer/NewConsumer.java

NewConsumer deprecated polling API update and singletonList

NewConsumer deprecated polling API update and singletonList

---

README.md

README markdown Update for consumer offsets Commit availability 

README markdown Update for consumer offsets Commit availability 

---

README.md

Update the `markdown` file Linkedin's Xinfra Rebranding.

Linkedin's Xinfra Rebranding

---

build.gradle
config/log4j2.properties
src/main/java/com/linkedin/kmf/services/ConsumeMetrics.java

bump up kafka-clients version.

bump up kafka-clients version.

---

src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

Export offset-committed-avg sensor

---

src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

Xinfra Monitor change commit-availability sensor to correct type

Xinfra Monitor change commit-availability sensor to correct type

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

Commit 6403e638e423969c04004876073cff23b1be1aec introduced a regression due to which ZK connections opened by MultiClusterTopicManagementService aren't recycled (see #192).
This commit attempts to fix that issue by wrapping auto-closable `KafkaZkClient` with try-with-resources statement.

#192 fix: close ZK connections cleanly

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java

1 - removes unneeded try catch block
2 - _commitAvailabilityMetrics._failedCommitOffsets.record(); is already recorded in the previous code portion.

Remove unneeded Try Catch Block 

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java

Add clarification of timestamp in records lost log

Add clarification of timestamp in records lost log

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java

Addition of JavaDoc for Consume Service

Addition of JavaDoc for Consume Service

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java

1 - Update to use meaningful constructor variables in the class.
2 - Addition of JavaDoc to the same constructor for information

Meaningful constructor variables and Addition of JavaDoc

---

src/main/java/com/linkedin/kmf/services/ProduceService.java

LOG errors lines have wrong number of arguments in ProduceService

LOG errors lines have wrong number of arguments in ProduceService

---

src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java

Addition of topic logs in `consumeService` and  `produceService`
```Signed-off-by: Andrew Choi <li_andchoi@microsoft.com>```

Addition of topic logs in consumeService and  produceService

---

.gitignore

Update .gitignore for minor unit tests that needs not be exposed to origin master
```Signed-off-by: Andrew Choi <li_andchoi@microsoft.com>```

Update .gitignore for minor unit tests that needs not be exposed to origin master

---

build.gradle
src/main/java/com/linkedin/kmf/common/ConsumerGroupCoordinatorUtils.java
src/main/java/com/linkedin/kmf/consumer/NewConsumer.java
src/main/java/com/linkedin/kmf/consumer/NewConsumerConfig.java
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/ConsumerFactoryImpl.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/test/java/com/linkedin/kmf/consumer/NewConsumerTest.java
src/test/java/com/linkedin/kmf/services/TopicManagementServiceTest.java

Xinfra Monitor Consumer Group Coordinator Assignment.
```
1. Implement Consumer Group Coordinator Assignment.
2. Bump up dependencies on Kafka and Kafka Client
```

Xinfra Monitor Consumer Group Coordinator Assignment

---

bin/kafka-monitor-start.sh
bin/windows/kafka-monitor-start.bat
bin/windows/kmf-run-class.bat
src/main/java/com/linkedin/kmf/XinfraMonitor.java
src/test/java/com/linkedin/kmf/KafkaMonitorTest.java

`Xinfra Monitor` Rebranding Operation from Kafka Monitor
```Signed-off-by: Andrew Choi <li_andchoi@microsoft.com>```

Xinfra Monitor Rebranding Operation from Kafka Monitor

---

src/main/java/com/linkedin/kmf/services/ConsumerFactoryImpl.java

Fallback to regular constructor parameters if the constructor doesn't include AdminClient.

Fallback to regular constructor parameters if the constructor doesn't include AdminClient.

---

README.md
config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/XinfraMonitor.java
src/main/java/com/linkedin/kmf/common/Utils.java
src/test/java/com/linkedin/kmf/XinfraMonitorTest.java

Xinfra Rebranding Continuation Part II

Xinfra Rebranding Continuation Part II

---

README.md

Update README for xinfra-monitor-start.sh

Update README for xinfra-monitor-start.sh

---

webapp/index.html

Minor, Update web application index HTML file -- Updated license year to `2020`

Minor, Update web application index HTML file -- Updated license year to 2020

---

src/main/java/com/linkedin/kmf/apps/MultiClusterMonitor.java
src/main/java/com/linkedin/kmf/services/Service.java
src/main/java/com/linkedin/kmf/services/SignalFxMetricsReporterService.java

- code cleanup of unnecessary declarations and types

Code cleanup of unnecessary declarations and types.

---

README.md

Update README.md with the list of available metrics emitted by XM

Update README.md with the list of available metrics emitted by XM

---

src/main/java/com/linkedin/kmf/XinfraMonitorConstants.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/metrics/ProduceMetrics.java

Migration of ProduceMetrics (Sensor) class to metrics package

Migration of ProduceMetrics (Sensor) class to metrics package

---

.github/workflows/gradle-publish.yml

TODO: Populate The USERNAME and TOKEN which needs to correspond to the credentials environment variables used in
the publishing section of your build.gradle

Populate Gradle Publish workflow YML file

---

.github/workflows/stale.yml

Create stale.yml and Mark stale issues and pull requests

Create stale.yml and Mark stale issues and pull requests

---

config/log4j2.properties
src/main/java/com/linkedin/kmf/services/ClusterTopicManipulationService.java

Implementation of whether the Topic Describe API is Successful or Not.

Implementation of whether the Topic Describe API is Successful or Not.

---

config/xinfra-monitor.properties
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/kmf/services/ClusterTopicManipulationService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/metrics/ClusterTopicManipulationMetrics.java
src/main/java/com/linkedin/kmf/services/metrics/XinfraMonitorMetrics.java

ClusterTopicManipulationService - 
1 - Topic Deletion Logic Implementation
2 - The Addition of Sensors/Metrics for Creation and Deletion Monitoring.

ClusterTopicManipulationService - Topic Deletion and Addition of Sensors/Metrics

---

.github/labeler.yml
.github/workflows/label.yml

1 - Create label.yml
2 - Add a Pull Request Labeler / triage (pull_request)

Add a Pull Request Labeler / triage (pull_request)

---

README.md

Update README.md with greetings and mark stale issues + PRs

Update README.md with greetings and mark stale issues + PRs

---

config/xinfra-monitor.properties

1 - Addition "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-avg",       
2 - Addition of "kmf.services:type=cluster-topic-manipulation-service,name=*:topic-deletion-metadata-propagation-ms-max"

cluster topic-deletion-metadata-propagation-ms metrics

---

src/main/java/com/linkedin/kmf/XinfraMonitorConstants.java
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/kmf/services/OffsetCommitService.java
src/main/java/com/linkedin/kmf/services/OffsetCommitServiceFactory.java
src/main/java/com/linkedin/kmf/services/configs/CommonServiceConfig.java
src/test/java/com/linkedin/kmf/services/OffsetCommitServiceTest.java

**OffsetCommitService Implementation**
1. Monitoring of a defined, particular Consumer Group's Coordinator
2. Runs on an interval and calculates to availability of the coordinator's acceptance percentage of offset commit requests.
`Follow up PRs`:
1 - TODO: add unit testing for the Service class.
2 - TODO: add metrics emission using Sensors for determining availability.
3 - TODO: allow users to define as many consumer groups as they want and create as many monitoring of coordinators for them.

OffsetCommitService of the consumer group coordinator

---

config/xinfra-monitor.properties
src/main/java/com/linkedin/kmf/services/OffsetCommitService.java

**Addition of offset-commit-service configurations to the config/xinfra-monitor.properties file.**

Addition of offset-commit-service configurations to the config/xinfra-monitor.properties file.

---

config/xinfra-monitor.properties

Update to new Xinfra Monitor package names within properties file

Update to new Xinfra Monitor package names within properties file

---

.github/labeler.yml
bin/windows/kmf-run-class.bat

_**Labeler and the run-class file to have updated package name.**_

Labeler and the run-class file to have updated package name.

---

bin/windows/kafka-monitor-start.bat

Update kafka-monitor-start.bat file with the rebranding changes.

Update kafka-monitor-start.bat file with the rebranding changes.

---

config/xinfra-monitor.properties

fixes https://github.com/linkedin/kafka-monitor/issues/311

Resolve Startup fail with Missing required configuration "topic" which has no default value.

---

src/main/java/com/linkedin/xinfra/monitor/services/ClusterTopicManipulationService.java
src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/xinfra/monitor/topicfactory/DefaultTopicFactory.java
src/main/java/com/linkedin/xinfra/monitor/topicfactory/TopicFactory.java

Kafka 2.4 KIP-455 - Update TopicFactory Interface and DefaultTopicFactory Implementation to use AdminClient

Kafka 2.4 KIP-455 - Update TopicFactory Interface and DefaultTopicFactory Implementation to use AdminClient

---

config/xinfra-monitor.properties
src/main/java/com/linkedin/xinfra/monitor/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/xinfra/monitor/services/configs/TopicManagementServiceConfig.java

Boolean switch for XM's enabling and disabling topic management service

Boolean switch for XM's enabling and disabling topic management service

---

src/main/java/com/linkedin/xinfra/monitor/services/ClusterTopicManipulationService.java
src/main/java/com/linkedin/xinfra/monitor/services/ConsumeService.java
src/main/java/com/linkedin/xinfra/monitor/services/DefaultMetricsReporterServiceFactory.java
src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/xinfra/monitor/services/OffsetCommitService.java
src/main/java/com/linkedin/xinfra/monitor/services/ProduceService.java
src/main/java/com/linkedin/xinfra/monitor/services/StatsdMetricsReporterServiceFactory.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/CommitAvailabilityMetrics.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/CommitLatencyMetrics.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/ConsumeMetrics.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/OffsetCommitServiceMetrics.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/ProduceMetrics.java
src/main/java/com/linkedin/xinfra/monitor/services/metrics/XinfraMonitorMetrics.java

https://github.com/linkedin/kafka-monitor/pull/327#issue-534073964
Xinfra Monitor - Performance, Optimization, Refactoring, Upgrades, Removal of Deprecations #327

Xinfra Monitor - Performance, Optimization, Refactoring, Upgrades, Removal of Deprecations

---

NOTICE

Update NOTICE with Copyright Years

Update NOTICE with Copyright Years

---

LICENSE

Update LICENSE with License Copyright Years

Update LICENSE with License Copyright Years

---

src/main/java/com/linkedin/xinfra/monitor/XinfraMonitor.java
src/main/java/com/linkedin/xinfra/monitor/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/xinfra/monitor/services/ClusterTopicManipulationService.java
src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/xinfra/monitor/services/ProduceService.java
src/main/java/com/linkedin/xinfra/monitor/topicfactory/DefaultTopicFactory.java
src/main/java/com/linkedin/xinfra/monitor/topicfactory/TopicFactory.java

1. Add logging to the MultiClusterTopicManagementService class
2. Add a timeout to some admin client requests
3. Rename some variables with non-inclusive language

Refactor and clean up

---

.github/workflows/ci.yml

Setup workflow to test PR changes.

adds test workflow

---

.github/workflows/tag.yml

- fixes GA issue:
- https://github.com/linkedin/kafka-monitor/actions/runs/3716497441/jobs/6302894482
```
Run actions/setup-java@v3
Installed distributions
Trying to resolve the latest version from remote
Error: Could not find satisfied version for SemVer 1.8.
Available versions: 17.0.3, 17.0.1+12.1, 16.0.2+7.1, 11.0.15, 11.0.13+8.1
```

Test workflow java version
