build.gradle

Enable the test configuration on the tests project.
Remove dependency on junit as it has a conflicting license and kafka monitor does not use it anyway.
As there are not any unit tests anyway this should not have an negative impact and will allow others to write unit tests.

Use testng on the tests project and remove dependencies on junit. 

---

config/kafka-monitor.properties
services/src/main/java/com/linkedin/kmf/common/Utils.java
services/src/main/java/com/linkedin/kmf/services/ProduceService.java
services/src/main/java/com/linkedin/kmf/services/configs/ProduceServiceConfig.java
tests/src/main/java/com/linkedin/kmf/tests/BasicEndToEndTest.java

This is the first of several changes needed to automatically distribute monitored partitions over the all brokers.  This creates a topic if one has not already been created with twice as many partitions as brokers.
This change has been tested by starting a cluster of three brokers and then verifying that the monitor starts successfully and the log message about the topic starting shows up in the log.
This change should not break any existing processes used to create monitoring topics as the monitor will still use an existing topic for monitoring if it exists.

Automatically create a monitoring topic if one has not already been created.

---

services/src/main/java/com/linkedin/kmf/services/ConsumeService.java
services/src/main/java/com/linkedin/kmf/services/ProduceService.java

Currently a zookeeper config in ProduceService can be used to populate existingPartitionCount or create a new topic while the override zookeeper config will be passed to the actual producer. This allows only one zookeeper config to be specified.

Fix potential use of two separate zookeepers for the same producer

---

config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/kmf/common/Utils.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java
src/main/java/com/linkedin/kmf/services/configs/CommonServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/ProduceServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/TopicManagementServiceConfig.java
src/main/java/com/linkedin/kmf/tests/BasicEndToEndTest.java
src/test/java/com/linkedin/kmf/services/TopicManagementServiceTest.java

Topic creation is now a responsibility of the TopicManagementService and the ProducerService will non-blocking wait to produce until the topic is created.

Move topic creation from produce service to Topic Management Service.

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java

If user specifies a class under test package in the kafka-monitor.properties, KafkaMonitor should instantiate an instance of this class and map it to the App interface. The patch fixed a bug where such class will be instantiated and mapped into the Service interface.

KafkaMonitor should map class under Test package into App interface

---

src/main/java/com/linkedin/kmf/common/Utils.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java

Currently if we start KafkaMonitor without first creating the topic, the KafkaMonitor's metric will be NAN for up to 40 seconds. This is because the topic may be created after ProduceService starts and the ProduceService only detect topic creation or partition expansion every 40 seconds. This patch reduces the expected time to wait by scheduling the detection to run 1 seconds after ProduceService starts.
Also, we should catch and swallow ToipcExistsException in the TopicManagementService because consumer in the ConsumeService may create the topic when consumer subscribes to the topic if topic auto creation is enabled.

Allow ProduceService to start working sooner if the topic is created after ProduceService has started

---

docker/Dockerfile
docker/kafka-monitor-docker-entry.sh

- removes some non-existing folders from being added to the Docker image
- properly handle signals in Docker start script so that the Kafka Monitor process is getting stopped when receiving a SIGINT or SIGTERM signal.

Docker build hardening

---

config/log4j.properties

Correct the log4j additivity for com.linkedin.kmf.core.KafkaMonitor.

KafkaMonitor logger additivity in 0.8.2.2

---

config/prometheus-exporter.yaml

export to prometheus supported format using jmx exporter with this config file
with this config file, you will get something like following:
```
kmf_services_consume_service_single_cluster_monitor_records_delay_ms_avg 1.674074074074074
kmf_services_consume_service_single_cluster_monitor_records_lost_total 0.0
kmf_services_consume_service_single_cluster_monitor_consume_error_total 0.0
kmf_kafka_metrics_count_count 2.0
kmf_services_consume_service_single_cluster_monitor_consume_availability_avg 1.0
kmf_services_consume_service_single_cluster_monitor_records_duplicated_rate 0.0
kmf_services_consume_service_single_cluster_monitor_records_consumed_rate 4.51693851944793
kmf_services_consume_service_single_cluster_monitor_records_delayed_rate 0.0 …
```

export to prometheus

---

src/main/java/com/linkedin/kmf/services/StatsdMetricsReporterService.java

The current statsd client already appends the prefix at the beginning of the metric name. Unfortunately the current code was also appending the prefix. For example:
If `prefix` was `kafka-monitor`, the final metric name produced would be:
`kafka-monitor.kafka-monitor.produce_service.single-cluster-monitor.produce-availability-avg`
But in reality should be:
`kafka-monitor.produce_service.single-cluster-monitor.produce-availability-avg`
This PR solves that problem by letting the statsd client do the appending of the prefix and removing some of that logic in the `StatsdMetricsReporterService`

Fixes double appending of prefix in metrics name

---

build.gradle
checkstyle/checkstyle.xml
checkstyle/suppressions.xml
config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/services/SignalFxMetricsReporterService.java
src/main/java/com/linkedin/kmf/services/configs/SignalFxMetricsReporterServiceConfig.java

1. Adds a metrics reporting service to report the Kafka monitor metrics to SignalFx.
2. Suppress checkstyle of LinkedIn Corp. headers for SignalFx files
3. Add avg-delay metric per broker to determine latency for each broker from producer and consumer
SignalFx is monitoring platform that performs operational intelligence for data-driven DevOps

Add support for reporting metrics to SignalFx

---

config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/configs/MultiClusterTopicManagementServiceConfig.java

fix two issues:
1) Incorrectly availability for offline partition when setting  _treatZeroThroughputAsUnavailable to false and large producer timeout.
The sample history KMF keeps is 60 seconds, which means all samples expire after 60 seconds. If We have request timeout more than 60 seconds, there is some time window the reported availability will be 100% even some partitions are offline. 
2) preferred leader election is triggered while partition reassignment is still in progress.  This leads to potential issues a) the replica might be moved out of the selected PLE leader as a result of partition reassignment , and leads to multiple leadership movement. 2) the selected PLE leader might not be the preferred leader after reassignment.

fix incorrected calculation of availability and separate PLE routing from rebalance

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/topicfactory/DefaultTopicFactory.java
src/main/java/com/linkedin/kmf/topicfactory/TopicFactory.java

KMF today assign partitions or add new partitions to all kafka brokers in a cluster. However, there are use cases that we don't want KMF topic partitions to be created on certain brokers. For example, broker that is not in a healthy state and is being removed might not want to take any new KMF partitions.  This fix allows user to blacklist certain kafka brokers via topic factory so that blacklisted brokers will not be assigned new partitions or taking reassigned partitions. The default topic factory implementation doesn't blacklist any brokers. User can have custom implementation of topic factory where blacklisted broker info can be obtained dynamically.

allow brokers to be blacklisted when adding new partitions or reassigning partitions

---

src/main/java/com/linkedin/kmf/common/Utils.java

** jsonFromGenericRecord(..)** in `Utils` class enable `public` access such that external `dependencies` can have access to this method when needed.

JsonFromGenericRecord Method in Utils class Enable public access

---

build.gradle

Currently, to be able to use kafka-monitor, people need to clone the repo or download the automatic tarball/zip of the releases, then build with gradle, then launch kafka-monitor.
By building a distribution tarball/zip during the build with only the necessary content (no need of the `src` folder nor `build/classes`), the users can simply download this distribution package, unarchive it and use it directly.
Thoses distribution packages can be added as assets in the GitHub releases.
```shell
$ ./gradlew clean assembleDist
BUILD SUCCESSFUL in 4s
7 actionable tasks: 7 executed
$ ls -1 build/distributions/
kafka-monitor-2.0.8-SNAPSHOT.tar.gz
kafka-monitor-2.0.8-SNAPSHOT.zip
$ tar tvzf build/distributions/kafka-monitor-2.0.8-SNAPSHOT.tar.gz 
drwxr-xr-x 0/0               0 2019-12-12 10:28 …
```

Create a tarball/zip of all necessary files

---

README.md

Wiki page update for Application Configuration of KMF
[Application Configuration](https://github.com/linkedin/kafka-monitor/wiki/App-Configuration)

Wiki page update for Application Configuration of KMF

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java

This fixes https://github.com/linkedin/kafka-monitor/issues/195
The latest PR https://github.com/linkedin/kafka-monitor/pull/196 didn't fix the issue:
I was testing this and I got:
```
Exception in thread "main" java.lang.NoSuchMethodException: com.linkedin.kmf.services.ConsumeService.<init>(java.lang.String, java.util.concurrent.CompletableFuture, com.linkedin.kmf.services.ConsumerFactoryImpl)
at java.lang.Class.getConstructor0(Class.java:3082)
at java.lang.Class.getConstructor(Class.java:1825)
at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:79)
at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:187)
```
Then I cloned this repo, and modified the `kafka-monitor.properties` file, uncommented:
```json
"consume-service": {
"class.name": …
```

Fix for instantiating ConsumeService

---

config/kafka-monitor.properties

When the application is run, the logs aren't printing out the offline runnable count, and it's due to the wrongly configured report metric name for `"kmf:type=kafka-monitor,name=*:offline-runnable-count",`
Tested with ` "kmf:type=kafka-monitor:offline-runnable-count",` -> and the metric is correctly logged.

Correct naming for report metric: offline-runnable-count

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java
src/main/java/com/linkedin/kmf/apps/App.java
src/main/java/com/linkedin/kmf/apps/MultiClusterMonitor.java
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/kmf/services/ConsumeMetrics.java
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/ConsumerFactoryImpl.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/services/TopicManagementService.java
src/main/java/com/linkedin/kmf/tests/BasicEndToEndTest.java
src/test/java/com/linkedin/kmf/services/ConsumeServiceTest.java

This removes the cases where the Xinfra Monitor fails to locate the topic partitions for a topic. 
1 - Removal of Race Condition between `MultiClusterTopicManagementService` and `ProduceService/ConsumeService`
2 - Thread.sleep to ensure the `MultiClusterTopicManagementService` executes the operation of preparing topics (and creation of it if necessary), followed by the topic partitions.
3 - move the `topic-partitions-count` to `start()` ConsumeService such that the topic and partitions preparation is fully executed first by the `MultiClusterTopicManagementService` and `TopicManagementService` -> see (*1)
4 - Simplify the usage of  `CompletableFuture<Void>` by using only one of  `CompletableFuture<Void>` instead of two  `CompletableFuture<Void>`
(*1)
``` Sensor topicPartitionCount = …
```

Simplifications of CompletableFuture + Ensuring MultiClusterTopicManagementService performs the topic partitions operations first.

---

config/log4j2.properties

- Remove misconfigured 'stdout' appender
- Fix 'kafkaClientAppender' appender
- Fix use of system properties
- Add configuration to use 'kafkaClientAppender' for kafka logs

Fix log4j2 conf to use kafka-client.log file

---

src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

SingleClusterMonitor - Add More kmf.services metrics for commit-availability-service (failed commits)
```
"kmf.services:type=commit-availability-service,name=*:offsets-committed-total",
"kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-total",
"kmf.services:type=commit-availability-service,name=*:failed-commit-offsets-avg",
```

SingleClusterMonitor - Add More kmf.services metrics for commit-availability-service (failed commits)

---

config/kafka-monitor.properties
src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

**Append:**
"kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-avg",
"kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-max",
"kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-99th",
"kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-999th",
"kmf.services:type=commit-latency-service,name=*:commit-offset-latency-ms-9999th"
--> for consumer offset commit latency metrics.
**Remove:**
"kmf.services:type=commit-availability-service,name=*:commit-latency-avg",	
"kmf.services:type=commit-availability-service,name=*:commit-availability-avg",
--> `commit-latency-avg"` and `commit-availability-avg` are outdated names which is renamed to `commit-offset-latency-ms-avg`. 
Signed-off-by: Andrew Choi …

Metrics Export Service Config and Properties to include Commit-latency-service -> commit-offset-latency-ms-avg

---

src/main/java/com/linkedin/kmf/services/ConsumeMetrics.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/kmf/services/ProduceService.java
src/main/java/com/linkedin/kmf/services/configs/DefaultMetricsReporterServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/GraphiteMetricsReporterServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/KafkaMetricsReporterServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/SignalFxMetricsReporterServiceConfig.java
src/main/java/com/linkedin/kmf/services/configs/StatsdMetricsReporterServiceConfig.java

Performance Improvements with Collection.singletonList
1 - use `Collections.singletonList("kmf.services:*:*")`list for performance improvements
2 - Redundant assignments removal.
3 - Use MetricValue casted to double. 

Performance Improvements with Collection.singletonList

---

src/main/java/com/linkedin/kmf/services/ConsumeMetrics.java

MetricValue casted to double to avoid deprecated APIs.
```        double recordsDelayedRate = (double) metrics.metrics().get(metrics.metricName("records-delayed-rate", METRIC_GROUP_NAME, tags)).metricValue();```

MetricValue casted to double to avoid deprecated APIs.

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

`_adminClient.electPreferredLeaders`(...) is deprecated. 
Update the class method to use the new API for PreferredLeaderElections (PLE) in Kafka Clients 2.4.0.

PreferredLeaderElections (PLE) Kafka Clients 2.4.0

---

src/main/java/com/linkedin/kmf/common/Utils.java

1 - Minor codestyle spacing
2 - Add SuppressWarnings for "rawtypes"
3 - Add no inspections on rawtypes
4 - Fix `NoSuchFieldError DEFAULT_SSL_PRINCIPAL_MAPPING_RULES` when `KafkaMetricsReporterService` is executed by removing unnecessary elements in the log.
```
Exception in thread “main” java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.linkedin.kmf.KafkaMonitor.<init>(KafkaMonitor.java:86)
at com.linkedin.kmf.KafkaMonitor.main(KafkaMonitor.java:193) …
```

Fix NoSuchFieldError DEFAULT_SSL_PRINCIPAL_MAPPING_RULES

---

src/main/java/com/linkedin/kmf/services/CommitLatencyMetrics.java

Offset commit already in progress is not a critical error that should kill the process.
Some commit tasks (Futures threads) take longer to complete and due to the nature of async commits, some commits take longer. Thus, changing level of Logging to debug is sufficient here.

Change level of logging to debug for offset commit 

---

.circleci/config.yml
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

```
1 - minor spelling error in services/MultiClusterTopicManagementService
`satisifies`
2 - Get topicPartitionsWithRetry after Creation of Topic
3 - LOGGER renaming
4 - Mark CircleCI as TODO
```

Get topicPartitionsWithRetry and a minor spelling error in services/MultiClusterTopicManagementService

---

src/main/java/com/linkedin/kmf/apps/SingleClusterMonitor.java

`MultiClusterTopicmanagementService` should block until topic creation is fully `complete`
Chosen `option 1`. 
Option 1 -  block on the future
Option 2 - 
```
@Override
public void run() {
try {
_produceService = new ProduceService(props, name);
_consumeService = new ConsumeService(name, topicPartitionResult, consumerFactory);
_allServices = new ArrayList<>(SERVICES_INITIAL_CAPACITY);
_allServices.add(_topicManagementService);
_allServices.add(_produceService);
_allServices.add(_consumeService);
} catch (Exception e) {
LOG.error("Exception occurred while instantiating ProduceService and ConsumeService. ", e);
}
}
}).get();
// Waits for and blocks for _produceService and _consumeService instantiations inside run() to complete.
}
```

MulticlustertopicmanagementService should block until topic creation is fully complete

---

src/main/java/com/linkedin/kmf/common/Utils.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/test/java/com/linkedin/kmf/services/MultiClusterTopicManagementServiceTest.java

1.  Use createTopicIfNotExist instead of AdminClient
3. connects the _topicFactory interface’s createTopicIfNotExist.

Use createTopicIfNotExist instead of AdminClient

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/test/java/com/linkedin/kmf/services/MultiClusterTopicManagementServiceTest.java

- Random assignment of partition assignments when adding partitions periodically
- Justifications: regardless of the partition/replica assignments here, `maybeReassignPartitionAndElectLeader()` will reassign the partition as needed periodically.

Partition Assignments when adding new topic partitions

---

build.gradle
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

1. `apache.kafka` use version : '2.4.1' 
2. justification: the internal `kmf multiproduct` currently employs scala version _2.11.
3. Moreover, `Anasi` (or ELR tool) doesn't allow for intaking scala _2.11 with apache kafka code version 2.5.0 because the maven service doesn't have, and thus does not release, the scala _2.11 version 2.5.0 .
- we cannot bump up to scala version _2.13 in the kafka-monitoring multiproduct because there are many, many multiproduct dependencies on the scala version _2.11 that have not been ELR.ed yet.
----------------------------------------------------
Justifications for merging this:
the PR won’t break any dependencies because the bump to 2.5.0 happened very recently in this repository
2 - internal MP (xinfra monitor) can be bumped up to scala kafka_2.12 but …

apache kafka scala version 2.13 with code version 2.4.1

---

build.gradle

Most clients and mp at linkedin use scala version_2.12/2.11 anyway so it makes sense for the open source to monitor clusters with scala version 2.12 as well.
tested with local deploys.

Xinfra Monitor scala 2.12

---

build.gradle
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

`Use of org.apache.kafka - version: 2.3.1`
Justification:
-  Current linkedin kafka repository, `"kafka": "com.linkedin.kafka:kafka_2.12:2.3.0.20",` which internal kmf mp depends on, still uses version 2.3.0.20.
-  This linkedin kafka version uses `def getPartitionAssignmentForTopics(topics: Set[String]): Map[String, Map[Int, Seq[Int]]]` as its parameters for the method `getPartitionAssignmentForTopics`. 
-  However, the `compile group: 'org.apache.kafka', name: 'kafka_2.12', version: '2.4.1'` uses  `def getPartitionAssignmentForTopics(topics: Set[String]): Map[String, Map[Int, ReplicaAssignment]]`
-  Thus, apache kafka 2.4.1 is not backward compatible with internal kmf MP and linkedin kafka inside kmf MP. -> there is a discrepancy in method definition of linkedin kafka versus apache …

Use of org.apache.kafka - version: 2.3.1

---

build.gradle
src/main/java/com/linkedin/kmf/services/ConsumeService.java
src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

Our internal `kmf` mp replies not on apache kafka, but linkedin/kafka which still to this date replies on the old copy - 2.3.*.
It makes more sense to use java kafka-clients 2.3.1 rather than 2.4.1 to better monitor our kafka clusters. 
`compile group: 'org.apache.kafka', name: 'kafka-clients', version: '2.3.1'`

Update Apache kafka kafka-clients version 2.3.1

---

src/main/java/com/linkedin/kmf/KafkaMonitor.java
src/main/java/com/linkedin/kmf/services/KafkaMetricsReporterService.java

1. Ensure KafkaMetricsReporterSerivce carries the correct constructor parameters.
2. Abstract out the helper methods with `constructorContainsClass`
3. The way Service Instantiations are done within Kafka Monitor will be updated with `https://github.com/linkedin/kafka-monitor/pull/257`.
--------------------
testing:
```
produce.treat.zero.throughput.as.unavailable = true
topic = kafka-monitor-topic1
zookeeper.connect = localhost:2181
(com.linkedin.kmf.services.configs.ProduceServiceConfig)
[2020-05-29 14:34:57,457] INFO produce-service/ProduceService is initialized. (com.linkedin.kmf.services.ProduceService)
[2020-05-29 14:34:57,468] INFO KafkaMetricsReporterServiceConfig values:
bootstrap.servers = localhost:9092
report.interval.sec = 3
report.kafka.topic.replication.factor = 1 …
```

Ensure KafkaMetricsReporterSerivce carries the correct constructor parameters.

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java
src/test/java/com/linkedin/kmf/services/MultiClusterTopicManagementServiceTest.java

The partition count you are increasing the partitions by should equal the actual size of the new partition assignments.
This PR achieves this. 
For instance: 
old partitions count = 5
new partitions count = 11
increase in partitions = 6
the size of the new partition assignments ought to be be 6 also.
**Note: Random assignment is adequate here because the periodic runnable for maybeReassignPartitions runs the reassignment operation on an interval.**
```
2020/06/04 17:00:32.200 ERROR [MultiClusterTopicManagementService] [krc-multi-cluster-topic-management-service] [kafka-monitoring] [] krc/MultiClusterTopicManagementService will stop due to error.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicaAssignmentException: Increasing the number of partitions by …
```

Update Providing number of assignments by which the number of partitions was increased

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

Set is unordered and doesn't allow for duplicates.
List is ordered and allows for duplicates.
Converting Set -> List for O(1) runtime complexity in lieu of O(n) caused by the usage of List.
Set -> List should be safe in this case since the Set<brokerMetadata> contains non-duplicated values.
TopicFactory interface declares the following member functions. Changing this method to return List could break the backward compatibility
```Set<Integer> getBlackListedBrokers(String zkUrl);```

Conversion of Set to List for BrokerMetadata Collection

---

.travis.yml

1. Travis CI has deprecated the use of the key `skip_cleanup`. 
2. Thus, have Travis CI use clean up instead of the deprecated skip_cleanup under .travis YML file
Why?
- Such that the following tests don't fail.
```
1. continuous-integration/travis-ci/pr — The Travis CI build passed
2. continuous-integration/travis-ci/push — The Travis CI build passed
```

Travis CI clean up instead of the deprecated skip_cleanup under .travis YML file

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

No need to block on the result of the new partition creation. This allows for running the `TopicManagementRunnable` to run more asynchronously as the separate thread for partition creation KafkaFuture will run asynchronously in the background.
This allows for maybeReassignPartitionAndElectLeader to run before maybeAddPartitions in some cases. For example, if reassignment of partitions is needed before adding new partitions. 
With this asynchronous nature, KMF is allowed to, if needed, shuffle the partitions prior to adding new partitions to the cluster topic.

No need to block on the result of the new partition creation

---

config/xinfra-monitor.properties

Addition of cluster-topic-manipulation-service and reporter-kafka-service in the xinfra monitor config

Addition of cluster-topic-manipulation-service and reporter-kafka-service in the xinfra monitor config

---

src/main/java/com/linkedin/kmf/services/MultiClusterTopicManagementService.java

1 - there is no need to block on the result of electPreferredLeaders within the topic management service.

Implement a non-blocking triggerPreferredLeaderElection

---

config/xinfra-monitor.properties
src/main/java/com/linkedin/xinfra/monitor/common/Utils.java
src/main/java/com/linkedin/xinfra/monitor/services/ClusterTopicManipulationService.java
src/main/java/com/linkedin/xinfra/monitor/services/ClusterTopicManipulationServiceFactory.java

Closes #306 
Addition of BlackListed Brokers to support KPC in cluster-topic-manipulation-service
This is a known issue on the open source Kafka Monitor. 
https://github.com/linkedin/kafka-monitor/issues/306 
1 - Related to KPC brokers (kafka preferred controller nodes), where topics for this class were created with replicas set on the preferred controller nodes as well.
2- Causing CruiseControl's UnfixableGoalViolation. Causes replicas to exist in preferred controller brokers. 
3 - topic: xinfra-monitor-cluster-topic-manipulation-service-topic with a different suffix each time.

Addition of BlackListed Brokers to support KPC in cluster-topic-manipulation-service

---

bin/windows/kafka-monitor-start.bat

Renamed main class path in bin/windows/kafka-monitor-start which is now sync with other files.

Issue #297: Fixed path in windows/kafka-monitor-start

---

bin/single-cluster-monitor.sh
docker/Dockerfile

After cloning the project, I found that `docker/Dockerfile` is not able to build due to the path error of kafka-monitor-start.sh. Also com/linkedin/kmf/apps/SingleClusterMonitor path was wrong in `bin/single-cluster-monitor.sh` file.

path fix for docker/Dockerfile and bin/single-cluster-monitor.sh

---

README.md

Removal of :
```
Open ```localhost:8000/index.html``` in your web browser.
You can edit webapp/index.html to easily add new metrics to be displayed.
curl localhost:8778/jolokia/read/kmf.services:type=produce-service,name=*/produce-availability-avg
curl localhost:8778/jolokia/read/kmf.services:type=consume-service,name=*/consume-availability-avg
You can query other JMX metric value as well by substituting object-name and
attribute-name of the JMX metric in the query above.
```
https://github.com/linkedin/kafka-monitor/issues/312
@smccauliff

Update README.md with Jolokia deprecation information

---

build.gradle
src/main/java/com/linkedin/xinfra/monitor/common/Utils.java
src/main/java/com/linkedin/xinfra/monitor/services/ConsumeService.java
src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java

`Kafka 2.4` + KIP-455 for Xinfra Monitor `Multi Cluster Topic Management Service` 
Total extends CumulativeSum : A non-sampled cumulative total maintained over all time.
This is a non-sampled version of {@link WindowedSum}.
Total is deprecated since 2.4. Recommended to use {@link CumulativeSum} instead.
(New) CumulativeSum: A non-sampled cumulative total maintained over all time.
This is a non-sampled version of {@link WindowedSum}.

 Kafka 2.4 + KIP-455 for Xinfra Monitor Multie Cluster Topic Management Service 

---

src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java

Change the topic configuration update to use `AdminClient`.
With first commit of this PR, behavior is like this (without the linebreaks, added for clarity) (listing all existing values then future values for every config):
```
[2020-10-09 19:28:21,161] INFO MultiClusterTopicManagementService will overwrite properties of the topic xinfra-monitor-topic in cluster from
Config(entries=[
ConfigEntry(name=compression.type, value=producer, source=DYNAMIC_TOPIC_CONFIG, isSensitive=false, isReadOnly=false, synonyms=[]),
ConfigEntry(name=confluent.value.schema.validation, value=false, source=DYNAMIC_TOPIC_CONFIG, isSensitive=false, isReadOnly=false, synonyms=[]),
ConfigEntry(name=leader.replication.throttled.replicas, value=, source=DYNAMIC_TOPIC_CONFIG, isSensitive=false, isReadOnly=false, …
```

Replace last use of ZkClient by AdminClient equivalent

---

.gitignore
src/main/java/com/linkedin/xinfra/monitor/apps/SingleClusterMonitor.java
src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java
src/main/java/com/linkedin/xinfra/monitor/services/configs/TopicManagementServiceConfig.java
src/test/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementServiceTest.java

Config props added:
1. `topic-management.topicAddPartitionEnabled`
2. `topic-management.topicReassignPartitionAndElectLeaderEnabled`
Both default to `true` for backward compatibility.

Add two config properties to disable the add-topic-partition procedure and the topic-reassig-partition-and-leader-elect procedure respectively

---

src/main/java/com/linkedin/xinfra/monitor/services/metrics/CommitLatencyMetrics.java

Before distributing a new release to `Bintray`, `Travis` runs a gradle task to check for syntactic correctness of javadoc (i.e. `Task :javadoc`). As a result, any syntax error on JavaDoc prevents publishing a new version.
A recent patch (see https://github.com/linkedin/kafka-monitor/commit/343f6fa38a8a519b76003fee74b33e781627eced) introduced a JavaDoc error, which causes the following failure:
```
> Task :javadoc
/home/travis/build/linkedin/kafka-monitor/src/main/java/com/linkedin/xinfra/monitor/services/metrics/CommitLatencyMetrics.java:64: error: exception not thrown: java.lang.Exception
* @throws Exception if the offset commit is already in progress.
^
/home/travis/build/linkedin/kafka-monitor/src/main/java/com/linkedin/xinfra/monitor/services/metrics/CommitLatencyMetrics.java:41: …
```

Fix bad javadoc causing Travis deployment failure

---

src/main/java/com/linkedin/xinfra/monitor/common/Utils.java

Hello,
This is a fix for the issue https://github.com/linkedin/kafka-monitor/issues/325. (Closed but not solved).
When creating a ClusterTopicManipulationService topic, the constructor uses a Hasmap containing the brokers id for each replica partition.
The problem is that has it is, the same broker id can be repeated.
With this fix, a simple shuffle of the brokers allows a random repartition of the brokers ids.
No need for the while loop.
Thanks

Fix replicasAssignment Hashmap

---

config/xinfra-monitor.properties

Update xinfra-monitor.properties with working example for statsd, as previous class.name is now deprecated/invalid.

Update statsd sample for Xinfra Monitor

---

build.gradle
src/main/java/com/linkedin/xinfra/monitor/common/Utils.java
src/main/java/com/linkedin/xinfra/monitor/services/GraphiteMetricsReporterService.java
src/main/java/com/linkedin/xinfra/monitor/services/SignalFxMetricsReporterService.java
src/main/java/com/linkedin/xinfra/monitor/services/StatsdMetricsReporterService.java

Use less ancient avro, maintain same wire format by @radai-rosenblatt

Use less ancient avro, maintain same wire format by @radai-rosenblatt

---

build.gradle
src/main/java/com/linkedin/xinfra/monitor/services/OffsetCommitService.java

bump dependencies: kafka and zookeeper
- 'kafka_2.12', version: '2.4.0' -> 'kafka_2.12', version: '2.8.2'
- 'kafka-clients', version: '2.3.1' -> 'kafka-clients', version: '2.8.2'
- zookeeper 3.5.6 -> 3.8.0
new `NetworkClient` arguments:
1. `long connectionSetupTimeoutMs`,
2. `long connectionSetupTimeoutMaxMs`
are described in https://issues.apache.org/jira/browse/KAFKA-9893 and corresponding PRs:
1. https://github.com/apache/kafka/pull/8544
2. https://github.com/apache/kafka/pull/8683
1. ./gradlew build

bump dependencies: kafka and zookeeper

---

build.gradle

[CVE-2022-42889](https://github.com/advisories/GHSA-599f-7c49-w659) in avro-util:
> Arbitrary code execution in Apache Commons Text
closes https://github.com/linkedin/kafka-monitor/issues/379
1. ./gradlew build

bump avro-util: 0.2.81 -> 0.2.118

---

.github/workflows/greetings.yml
.github/workflows/tag.yml

from: https://github.com/linkedin/kafka-monitor/actions/runs/3299810452
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-java, actions/setup-java, actions/checkout
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
as well as run `greetings` workflow once

Address github actions deprecations

---

src/main/java/com/linkedin/xinfra/monitor/services/OffsetCommitService.java

- Exception
```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
at org.apache.kafka.common.config.AbstractConfig.getInt(AbstractConfig.java:173)
at com.linkedin.xinfra.monitor.services.OffsetCommitService.<init>(OffsetCommitService.java:132)
at com.linkedin.xinfra.monitor.services.OffsetCommitServiceFactory.createService(OffsetCommitServiceFactory.java:53)
at com.linkedin.xinfra.monitor.XinfraMonitor.<init>(XinfraMonitor.java:82)
at com.linkedin.xinfra.monitor.XinfraMonitor.main(XinfraMonitor.java:186)
```
- #378 PR introduced new [arguments for Network client `long connectionSetupTimeoutMs` and `long …

Fix arguments' types causing exception
